name: build release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: validate gradle-wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        id: jar
        run: ./gradlew build>> "$GITHUB_OUTPUT"
      - name: Get Mod Version
        id: ver
        run: echo "./gradlew -q printVersion" >> "$GITHUB_OUTPUT"
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: test release ${{ steps.ver.outputs.* }}
#      - name: publish release
#        uses: actions/upload-artifact@v3
#        with:
#          name: release
#          path: build/libs/
