name: build release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build
        uses: ./gradlew build
      - name: publish release
        uses: actions/upload-artefact@v2.2.4
        with:
          name: release
          path: build/libs/
