name: build release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: validate gradle-wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        id: built
        run: ./gradlew build
      - name: Get Mod Version
        id: ver
        run: echo "VER=$(./gradlew -q printVersion)" >> "$GITHUB_OUTPUT"
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar"
          name: KanyeQuoter-${{ steps.ver.outputs.VER }}
          tag: ${{ steps.ver.outputs.VER }}
          allowUpdates: true
          replacesArtefacts: true
